apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: locustio/locust
          args:
            - "-f"
            - "/mnt/locust/locustfile.py"
            - "--worker"
            - "--master-host=locust-master"
          volumeMounts:
            - name: locust-script-volume
              mountPath: /mnt/locust
      volumes:
        - name: locust-script-volume
          configMap:
            name: locust-script
