apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  selector:
    app: locust-master
  ports:
    - name: web-ui
      port: 8089
      targetPort: 8089
    - name: master-1
      port: 5557
      targetPort: 5557
    - name: master-2
      port: 5558
      targetPort: 5558
